const FLAG_IMAGE_SMOOTHING_DISABLED = false;
const FLAG_BOUNDS_CHECK_ROOM_TRANSITIONS = true;
const FLAG_RECORD_PREVIOUS_FRAMES = false;
const FLAG_DEBUG_PHYSICS = false;
const FLAG_CHECK_TILES_VALID = true;
const FLAG_CHECK_CIRCULAR_CARRYING = true;
const FLAG_CARRIER_TURNS_CARRIED = true;